parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: fopac
    database_user: fopac
    database_password: fopac
    app.mail: support@fopac.cu.cc
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c1a56fbbf58ecf42175d71010fa5b88d81
    clean_secret: 1e0c1293232d317fe9830787f3d9ae7a89be3004e0ae49e564b7e97aa1142aa1
    database_path: null
