_welcome:
    path: /
    defaults: 
        _controller: FrameworkBundle:Template:template
        template: 'FOPACChatBundle:Static:index.html.twig'

fopac_chat:
    resource: "@FOPACChatBundle/Resources/config/routing.yml"
    prefix:   /

