parameters:
#    fopac_chat.example.class: FOPAC\ChatBundle\Example

services:
#    fopac_chat.example:
#        class: %fopac_chat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
