<?php

namespace FOPAC\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	public function findAllNewest($lastId, $room)
	{
		return $this->getEntityManager()
            ->createQuery('SELECT msg FROM FOPACChatBundle:Message msg WHERE (msg.room = ' . $room->getId() . ' AND msg.id > ' . $lastId . ') ORDER BY msg.id ASC')
            ->getResult();
	}

	public function findOlder($firstId, $room, $limit)
	{
		return $this->getEntityManager()
            ->createQuery('SELECT msg FROM FOPACChatBundle:Message msg WHERE (msg.room = ' . $room->getId() . ' AND msg.id < ' . $firstId . ') ORDER BY msg.id DESC')
            ->setMaxResults($limit)
            ->getResult();
	}
}
 